class AddDefaultsToPlayerInfoUpdates < ActiveRecord::Migration[5.0]
  def change
    change_column_default :player_info_updates, :logins, from: nil, to: 0
    change_column_default :player_info_updates, :activity, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_won, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_draw, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_lost, from: nil, to: 0
    change_column_default :player_info_updates, :highest_beaten, from: nil, to: 0
    change_column_default :player_info_updates, :best_kill_streak, from: nil, to: 0
    change_column_default :player_info_updates, :defends_lost, from: nil, to: 0
    change_column_default :player_info_updates, :defends_won, from: nil, to: 0
    change_column_default :player_info_updates, :defends_draw, from: nil, to: 0
    change_column_default :player_info_updates, :xanax_taken, from: nil, to: 0
    change_column_default :player_info_updates, :ecstasy_taken, from: nil, to: 0
    change_column_default :player_info_updates, :times_traveled, from: nil, to: 0
    change_column_default :player_info_updates, :networth, from: nil, to: 0
    change_column_default :player_info_updates, :refills, from: nil, to: 0
    change_column_default :player_info_updates, :stat_enhancers_used, from: nil, to: 0
    change_column_default :player_info_updates, :medical_items_used, from: nil, to: 0
    change_column_default :player_info_updates, :weapons_bought, from: nil, to: 0
    change_column_default :player_info_updates, :bazaar_customers, from: nil, to: 0
    change_column_default :player_info_updates, :bazaar_sales, from: nil, to: 0
    change_column_default :player_info_updates, :bazaar_profit, from: nil, to: 0
    change_column_default :player_info_updates, :points_bought, from: nil, to: 0
    change_column_default :player_info_updates, :points_sold, from: nil, to: 0
    change_column_default :player_info_updates, :items_bought_abroad, from: nil, to: 0
    change_column_default :player_info_updates, :items_bought, from: nil, to: 0
    change_column_default :player_info_updates, :trades, from: nil, to: 0
    change_column_default :player_info_updates, :items_sent, from: nil, to: 0
    change_column_default :player_info_updates, :auctions_won, from: nil, to: 0
    change_column_default :player_info_updates, :auctions_sold, from: nil, to: 0
    change_column_default :player_info_updates, :money_mugged, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_stealthed, from: nil, to: 0
    change_column_default :player_info_updates, :critical_hits, from: nil, to: 0
    change_column_default :player_info_updates, :respect, from: nil, to: 0
    change_column_default :player_info_updates, :rounds_fired, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_ran_away, from: nil, to: 0
    change_column_default :player_info_updates, :defends_ran_away, from: nil, to: 0
    change_column_default :player_info_updates, :people_busted, from: nil, to: 0
    change_column_default :player_info_updates, :failed_busts, from: nil, to: 0
    change_column_default :player_info_updates, :bails_bought, from: nil, to: 0
    change_column_default :player_info_updates, :bails_spent, from: nil, to: 0
    change_column_default :player_info_updates, :viruses_coded, from: nil, to: 0
    change_column_default :player_info_updates, :city_finds, from: nil, to: 0
    change_column_default :player_info_updates, :bounties_placed, from: nil, to: 0
    change_column_default :player_info_updates, :bounties_received, from: nil, to: 0
    change_column_default :player_info_updates, :bounties_collected, from: nil, to: 0
    change_column_default :player_info_updates, :bounty_rewards, from: nil, to: 0
    change_column_default :player_info_updates, :bounties_spent, from: nil, to: 0
    change_column_default :player_info_updates, :revives, from: nil, to: 0
    change_column_default :player_info_updates, :revives_received, from: nil, to: 0
    change_column_default :player_info_updates, :trains_received, from: nil, to: 0
    change_column_default :player_info_updates, :drugs_taken, from: nil, to: 0
    change_column_default :player_info_updates, :overdoses, from: nil, to: 0
    change_column_default :player_info_updates, :merits_bought, from: nil, to: 0
    change_column_default :player_info_updates, :personals_placed, from: nil, to: 0
    change_column_default :player_info_updates, :classifieds_placed, from: nil, to: 0
    change_column_default :player_info_updates, :mail_sent, from: nil, to: 0
    change_column_default :player_info_updates, :friend_mail_sent, from: nil, to: 0
    change_column_default :player_info_updates, :faction_mail_sent, from: nil, to: 0
    change_column_default :player_info_updates, :company_mail_sent, from: nil, to: 0
    change_column_default :player_info_updates, :spouse_mail_sent, from: nil, to: 0
    change_column_default :player_info_updates, :largest_mug, from: nil, to: 0
    change_column_default :player_info_updates, :canabis_taken, from: nil, to: 0
    change_column_default :player_info_updates, :ketamine_taken, from: nil, to: 0
    change_column_default :player_info_updates, :lsd_taken, from: nil, to: 0
    change_column_default :player_info_updates, :opium_taken, from: nil, to: 0
    change_column_default :player_info_updates, :shrooms_taken, from: nil, to: 0
    change_column_default :player_info_updates, :speed_taken, from: nil, to: 0
    change_column_default :player_info_updates, :pcp_taken, from: nil, to: 0
    change_column_default :player_info_updates, :vicodin_taken, from: nil, to: 0
    change_column_default :player_info_updates, :mechanical_hits, from: nil, to: 0
    change_column_default :player_info_updates, :artillery_hits, from: nil, to: 0
    change_column_default :player_info_updates, :clubbed_hits, from: nil, to: 0
    change_column_default :player_info_updates, :temp_hits, from: nil, to: 0
    change_column_default :player_info_updates, :machine_gun_hits, from: nil, to: 0
    change_column_default :player_info_updates, :pistol_hits, from: nil, to: 0
    change_column_default :player_info_updates, :rifle_hits, from: nil, to: 0
    change_column_default :player_info_updates, :shotgun_hits, from: nil, to: 0
    change_column_default :player_info_updates, :smg_hits, from: nil, to: 0
    change_column_default :player_info_updates, :piercing_hits, from: nil, to: 0
    change_column_default :player_info_updates, :slashing_hits, from: nil, to: 0
    change_column_default :player_info_updates, :argentina_travel, from: nil, to: 0
    change_column_default :player_info_updates, :mexico_travel, from: nil, to: 0
    change_column_default :player_info_updates, :dubai_travel, from: nil, to: 0
    change_column_default :player_info_updates, :hawaii_travel, from: nil, to: 0
    change_column_default :player_info_updates, :japan_travel, from: nil, to: 0
    change_column_default :player_info_updates, :london_travel, from: nil, to: 0
    change_column_default :player_info_updates, :south_africa_travel, from: nil, to: 0
    change_column_default :player_info_updates, :switzerland_travel, from: nil, to: 0
    change_column_default :player_info_updates, :china_travel, from: nil, to: 0
    change_column_default :player_info_updates, :canada_travel, from: nil, to: 0
    change_column_default :player_info_updates, :caymans_travel, from: nil, to: 0
    change_column_default :player_info_updates, :dump_finds, from: nil, to: 0
    change_column_default :player_info_updates, :dump_searches, from: nil, to: 0
    change_column_default :player_info_updates, :items_dumped, from: nil, to: 0
    change_column_default :player_info_updates, :days_as_donator, from: nil, to: 0
    change_column_default :player_info_updates, :times_jailed, from: nil, to: 0
    change_column_default :player_info_updates, :times_hospitalized, from: nil, to: 0
    change_column_default :player_info_updates, :attacks_assisted, from: nil, to: 0
    change_column_default :player_info_updates, :blood_withdrawn, from: nil, to: 0
    change_column_default :player_info_updates, :mission_credits, from: nil, to: 0
    change_column_default :player_info_updates, :contracts_completed, from: nil, to: 0
    change_column_default :player_info_updates, :duke_contracts_completed, from: nil, to: 0
    change_column_default :player_info_updates, :missions_completed, from: nil, to: 0
    change_column_default :player_info_updates, :medical_items_stolen, from: nil, to: 0
    change_column_default :player_info_updates, :spies_done, from: nil, to: 0
    change_column_default :player_info_updates, :best_damage, from: nil, to: 0
    change_column_default :player_info_updates, :kill_streak, from: nil, to: 0
    change_column_default :player_info_updates, :one_hit_kills, from: nil, to: 0
    change_column_default :player_info_updates, :money_invested, from: nil, to: 0
    change_column_default :player_info_updates, :invested_profit, from: nil, to: 0
    change_column_default :player_info_updates, :attack_misses, from: nil, to: 0
    change_column_default :player_info_updates, :attack_damage, from: nil, to: 0
    change_column_default :player_info_updates, :attack_hits, from: nil, to: 0
  end
end
