class CreatePlayerInfoUpdates < ActiveRecord::Migration[5.0]
  def change
    create_table :player_info_updates do |t|
      t.datetime :timestamp
      t.integer :level
      t.datetime :signup
      t.datetime :last_action
      t.references :player, foreign_key: true
      t.integer :awards
      t.integer :friends
      t.integer :enemies
      t.integer :karma
      t.integer :forum_posts
      t.string :role
      t.boolean :donator
      t.integer :max_life
      t.integer :company_id
      t.string :position
      t.references :spouse, references: :player
      t.references :faction, foreign_key: true
      t.integer :logins
      t.integer :activity
      t.integer :attacks_won
      t.integer :attacks_draw
      t.integer :attacks_lost
      t.integer :highest_beaten
      t.integer :best_kill_streak
      t.integer :defends_lost
      t.integer :defends_won
      t.integer :defends_draw
      t.integer :xan_taken
      t.integer :ecstasy_taken
      t.integer :times_traveled
      t.integer :networth
      t.integer :refills
      t.integer :stat_enhancers_used
      t.integer :medical_items_used
      t.integer :weapons_bought
      t.integer :bazaar_customers
      t.integer :bazaar_sales
      t.integer :bazaar_profit
      t.integer :points_bought
      t.integer :points_sold
      t.integer :items_bought_abroad
      t.integer :items_bought
      t.integer :trades
      t.integer :items_sent
      t.integer :auctions_won
      t.integer :auctions_sold
      t.integer :money_mugged
      t.integer :attacks_stealthed
      t.integer :critical_hits
      t.integer :respect
      t.integer :rounds_fired
      t.integer :attacks_ran_away
      t.integer :defends_ran_away
      t.integer :people_busted
      t.integer :failed_busts
      t.integer :bails_bought
      t.integer :bails_spent
      t.integer :viruses_coded
      t.integer :city_finds
      t.integer :bounties_placed
      t.integer :bounties_received
      t.integer :bounties_collected
      t.integer :bounty_rewards
      t.integer :bounties_spent
      t.integer :revives
      t.integer :revives_received
      t.integer :trains_received
      t.integer :drugs_taken
      t.integer :overdoses
      t.integer :merits_bought
      t.integer :personals_placed
      t.integer :classifieds_placed
      t.integer :mail_sent
      t.integer :friend_mail_sent
      t.integer :faction_mail_sent
      t.integer :company_mail_sent
      t.integer :spouse_mail_sent
      t.integer :largest_mug
      t.integer :canabis_taken
      t.integer :ketamine_taken
      t.integer :lsd_taken
      t.integer :opium_taken
      t.integer :shrooms_taken
      t.integer :speed_taken
      t.integer :pcp_taken
      t.integer :vicodin_taken
      t.integer :mechanical_hits
      t.integer :artillery_hits
      t.integer :clubbed_hits
      t.integer :temp_hits
      t.integer :machine_gun_hits
      t.integer :pistol_hits
      t.integer :rifle_hits
      t.integer :shotgun_hits
      t.integer :smg_hits
      t.integer :piercing_hits
      t.integer :slashing_hits
      t.integer :argentina_travel
      t.integer :mexico_travel
      t.integer :dubai_travel
      t.integer :hawaii_travel
      t.integer :japan_travel
      t.integer :london_travel
      t.integer :south_africa_travel
      t.integer :switzerland_travel
      t.integer :china_travel
      t.integer :canada_travel
      t.integer :caymans_travel
      t.integer :dump_finds
      t.integer :dump_searches
      t.integer :items_dumped
      t.integer :days_as_donator
      t.integer :times_jailed
      t.integer :times_hospitalized
      t.integer :attacks_assisted
      t.integer :blood_withdrawn
      t.integer :mission_credits
      t.integer :contracts_completed
      t.integer :duke_contracts_completed
      t.integer :missions_completed
    end
  end
end
