class DisallowNullsInPlayerInfoUpdates < ActiveRecord::Migration[5.0]
  def change
    change_column_null :player_info_updates, :logins, false
    change_column_null :player_info_updates, :activity, false
    change_column_null :player_info_updates, :attacks_won, false
    change_column_null :player_info_updates, :attacks_draw, false
    change_column_null :player_info_updates, :attacks_lost, false
    change_column_null :player_info_updates, :highest_beaten, false
    change_column_null :player_info_updates, :best_kill_streak, false
    change_column_null :player_info_updates, :defends_lost, false
    change_column_null :player_info_updates, :defends_won, false
    change_column_null :player_info_updates, :defends_draw, false
    change_column_null :player_info_updates, :xanax_taken, false
    change_column_null :player_info_updates, :ecstasy_taken, false
    change_column_null :player_info_updates, :times_traveled, false
    change_column_null :player_info_updates, :networth, false
    change_column_null :player_info_updates, :refills, false
    change_column_null :player_info_updates, :stat_enhancers_used, false
    change_column_null :player_info_updates, :medical_items_used, false
    change_column_null :player_info_updates, :weapons_bought, false
    change_column_null :player_info_updates, :bazaar_customers, false
    change_column_null :player_info_updates, :bazaar_sales, false
    change_column_null :player_info_updates, :bazaar_profit, false
    change_column_null :player_info_updates, :points_bought, false
    change_column_null :player_info_updates, :points_sold, false
    change_column_null :player_info_updates, :items_bought_abroad, false
    change_column_null :player_info_updates, :items_bought, false
    change_column_null :player_info_updates, :trades, false
    change_column_null :player_info_updates, :items_sent, false
    change_column_null :player_info_updates, :auctions_won, false
    change_column_null :player_info_updates, :auctions_sold, false
    change_column_null :player_info_updates, :money_mugged, false
    change_column_null :player_info_updates, :attacks_stealthed, false
    change_column_null :player_info_updates, :critical_hits, false
    change_column_null :player_info_updates, :respect, false
    change_column_null :player_info_updates, :rounds_fired, false
    change_column_null :player_info_updates, :attacks_ran_away, false
    change_column_null :player_info_updates, :defends_ran_away, false
    change_column_null :player_info_updates, :people_busted, false
    change_column_null :player_info_updates, :failed_busts, false
    change_column_null :player_info_updates, :bails_bought, false
    change_column_null :player_info_updates, :bails_spent, false
    change_column_null :player_info_updates, :viruses_coded, false
    change_column_null :player_info_updates, :city_finds, false
    change_column_null :player_info_updates, :bounties_placed, false
    change_column_null :player_info_updates, :bounties_received, false
    change_column_null :player_info_updates, :bounties_collected, false
    change_column_null :player_info_updates, :bounty_rewards, false
    change_column_null :player_info_updates, :bounties_spent, false
    change_column_null :player_info_updates, :revives, false
    change_column_null :player_info_updates, :revives_received, false
    change_column_null :player_info_updates, :trains_received, false
    change_column_null :player_info_updates, :drugs_taken, false
    change_column_null :player_info_updates, :overdoses, false
    change_column_null :player_info_updates, :merits_bought, false
    change_column_null :player_info_updates, :personals_placed, false
    change_column_null :player_info_updates, :classifieds_placed, false
    change_column_null :player_info_updates, :mail_sent, false
    change_column_null :player_info_updates, :friend_mail_sent, false
    change_column_null :player_info_updates, :faction_mail_sent, false
    change_column_null :player_info_updates, :company_mail_sent, false
    change_column_null :player_info_updates, :spouse_mail_sent, false
    change_column_null :player_info_updates, :largest_mug, false
    change_column_null :player_info_updates, :canabis_taken, false
    change_column_null :player_info_updates, :ketamine_taken, false
    change_column_null :player_info_updates, :lsd_taken, false
    change_column_null :player_info_updates, :opium_taken, false
    change_column_null :player_info_updates, :shrooms_taken, false
    change_column_null :player_info_updates, :speed_taken, false
    change_column_null :player_info_updates, :pcp_taken, false
    change_column_null :player_info_updates, :vicodin_taken, false
    change_column_null :player_info_updates, :mechanical_hits, false
    change_column_null :player_info_updates, :artillery_hits, false
    change_column_null :player_info_updates, :clubbed_hits, false
    change_column_null :player_info_updates, :temp_hits, false
    change_column_null :player_info_updates, :machine_gun_hits, false
    change_column_null :player_info_updates, :pistol_hits, false
    change_column_null :player_info_updates, :rifle_hits, false
    change_column_null :player_info_updates, :shotgun_hits, false
    change_column_null :player_info_updates, :smg_hits, false
    change_column_null :player_info_updates, :piercing_hits, false
    change_column_null :player_info_updates, :slashing_hits, false
    change_column_null :player_info_updates, :argentina_travel, false
    change_column_null :player_info_updates, :mexico_travel, false
    change_column_null :player_info_updates, :dubai_travel, false
    change_column_null :player_info_updates, :hawaii_travel, false
    change_column_null :player_info_updates, :japan_travel, false
    change_column_null :player_info_updates, :london_travel, false
    change_column_null :player_info_updates, :south_africa_travel, false
    change_column_null :player_info_updates, :switzerland_travel, false
    change_column_null :player_info_updates, :china_travel, false
    change_column_null :player_info_updates, :canada_travel, false
    change_column_null :player_info_updates, :caymans_travel, false
    change_column_null :player_info_updates, :dump_finds, false
    change_column_null :player_info_updates, :dump_searches, false
    change_column_null :player_info_updates, :items_dumped, false
    change_column_null :player_info_updates, :days_as_donator, false
    change_column_null :player_info_updates, :times_jailed, false
    change_column_null :player_info_updates, :times_hospitalized, false
    change_column_null :player_info_updates, :attacks_assisted, false
    change_column_null :player_info_updates, :blood_withdrawn, false
    change_column_null :player_info_updates, :mission_credits, false
    change_column_null :player_info_updates, :contracts_completed, false
    change_column_null :player_info_updates, :duke_contracts_completed, false
    change_column_null :player_info_updates, :missions_completed, false
    change_column_null :player_info_updates, :medical_items_stolen, false
    change_column_null :player_info_updates, :spies_done, false
    change_column_null :player_info_updates, :best_damage, false
    change_column_null :player_info_updates, :kill_streak, false
    change_column_null :player_info_updates, :one_hit_kills, false
    change_column_null :player_info_updates, :money_invested, false
    change_column_null :player_info_updates, :invested_profit, false
    change_column_null :player_info_updates, :attack_misses, false
    change_column_null :player_info_updates, :attack_damage, false
    change_column_null :player_info_updates, :attack_hits, false
  end
end
